#Installation of Numpy

In [ ]:
pip install numpy

In [ ]:
import numpy
print(numpy.__version__)

2.0.2


In [ ]:
import numpy as np

#Creation of Numpy Elements

In [ ]:
a = np.array
print(a)

<built-in function array>


In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


#Type functions in Numpy

In [ ]:
a = np.array([1,2,3])
print(a)
#Returns type of an array
print(type(a))
#Returns data types of elements inside the array
print(a.dtype)
#Returns dimensions of numpy array
print(a.ndim)

[1 2 3]
<class 'numpy.ndarray'>
int64
1


In [ ]:
a = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(a)
print(type(a))
print(a.dtype)
print(a.ndim)

[[1 2 3]
 [4 5 6]
 [6 7 8]]
<class 'numpy.ndarray'>
int64
2


#Sizes and shapes of Numpy

In [ ]:
a = np.array([[1,2,3,4,5,6]])
print(a.size) # no.of elements
print(a.shape) #(rows,columns)

6
(1, 6)


In [ ]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
print(arr.size)
print(arr.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)


#Accessing of elements in Numpy

In [ ]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[0,1])
print(a[2,1])
print(a[1,1])

[[1 2]
 [3 4]
 [5 6]]
2
6
4


#Functions in Numpy

In [ ]:
a = np.array([1,2,3,50,4,45,4])
print(a)
print(a.max())
print(a.min())
print(a.sum())

[ 1  2  3 50  4 45  4]
50
1
109


In [ ]:
# randn --> generates random number between (-1,0,1)

a = np.random.randn(3,4)
print(a)

[[-0.54379299  1.04612002 -2.19451621 -1.4535563 ]
 [ 0.24161563 -0.51187575  0.49864786 -0.61281045]
 [ 0.97335901  0.19363086 -0.03279141  0.47187911]]


In [ ]:
# Ranging function in numpy --> arange()

print(np.arange(12))

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
# Round function ---> around()

arr = np.array([12.2, 90.12, 12.54789, 52.85])
print(arr)
print(np.around(arr))
print(np.around(arr, 2) )

[12.2     90.12    12.54789 52.85   ]
[12. 90. 13. 53.]
[12.2  90.12 12.55 52.85]


#Numpy Broadcasting

In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a+b
print(c)

[ 3  6  9 12 15 18 21]


In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a-b
print(c)

[-1 -2 -3 -4 -5 -6 -7]


In [ ]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([2,4,6,8,10,12,14])
c = a*b
print(c)

[ 2  8 18 32 50 72 98]


In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print('*********************************')
at = a.T # Transpose --> rows changes to columns, columns changes to rows
print(at)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
*********************************
[[1 4 7]
 [2 5 8]
 [3 6 9]]


#Pandas

#Installation of Pandas

In [ ]:
pip install pandas

In [ ]:
import pandas as pd

#Pandas Series

In [ ]:
info = np.array(['A','B','C','D','E','F'])
a = pd.Series(info)
print(a)

0    A
1    B
2    C
3    D
4    E
5    F
dtype: object


In [ ]:
info = {'x':0,'y':1,'z':2}
a = pd.Series(info)
print(a)

x    0
y    1
z    2
dtype: int64


In [ ]:
arr = [1,2,3,4]
index = ['a','b','c','d']
x = pd.Series(arr,index)
print(x)

a    1
b    2
c    3
d    4
dtype: int64


#DataFrame

In [ ]:
df = pd.DataFrame()
print(df)
df

Empty DataFrame
Columns: []
Index: []


Empty DataFrame
Columns: []
Index: []

In [ ]:
x = ['Python','Pandas']

df = pd.DataFrame(x)
df

0
0  Python
1  Pandas

In [ ]:
info = {'ID':[101,102,103,104,105],'Department':['MEC','CEC','MPC','BIPC','HEC']}

df = pd.DataFrame(info)
df

ID Department
0  101        MEC
1  102        CEC
2  103        MPC
3  104       BIPC
4  105        HEC

In [ ]:
emp = ['Parker','John','Smith','William']
id = [102,107,109,111]

emp_series = pd.Series(emp)
id_series = pd.Series(id)

a = {'Emp':emp_series, 'ID':id_series}
df = pd.DataFrame(a)
df


Emp   ID
0   Parker  102
1     John  107
2    Smith  109
3  William  111

In [ ]:
info = {'One':[10,20,30,40,50],'Two':[100,200,300,400,500]}

df = pd.DataFrame(info)
df

One  Two
0   10  100
1   20  200
2   30  300
3   40  400
4   50  500

In [ ]:
df['Two']

0    100
1    200
2    300
3    400
4    500
Name: Two, dtype: int64

In [ ]:
df['Three'] = df['One'] * df['Two']
df

One  Two  Three
0   10  100   1000
1   20  200   4000
2   30  300   9000
3   40  400  16000
4   50  500  25000

In [ ]:
del df['One']
df

Two  Three
0  100   1000
1  200   4000
2  300   9000
3  400  16000
4  500  25000

#loc and iloc

In [ ]:
data = pd.Series(['a','b','c','d'], index = [1,3,5,7])
print(data)
print(data.loc[1])
print(data.iloc[1])

1    a
3    b
5    c
7    d
dtype: object
a
b


#   Wroking with CSV files
    #open empty Excel file
    #Click on file -> Save as -> (Choose the location of the current .py file)
    #Create a file name & choose the type as CSV (comma delimited)
    #Enter some values in the file

In [8]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('sample.csv')
df

ROLLNO NAME
0     101    A
1     102    B
2     103    C
3     104    D
4     105    E
5     106    F
6     107    G

In [4]:
df.head() #generates first 5 rows

ROLLNO NAME
0     101    A
1     102    B
2     103    C
3     104    D
4     105    E

In [5]:
df.tail() #generates lsat five rows

ROLLNO NAME
2     103    C
3     104    D
4     105    E
5     106    F
6     107    G

In [6]:
df

ROLLNO NAME
0     101    A
1     102    B
2     103    C
3     104    D
4     105    E
5     106    F
6     107    G

In [9]:
df.apply(np.max)

ROLLNO    107
NAME        G
dtype: object

In [10]:
df.apply(np.min)

ROLLNO    101
NAME        A
dtype: object

In [11]:
df.sort_values(by = 'ROLLNO')

ROLLNO NAME
0     101    A
1     102    B
2     103    C
3     104    D
4     105    E
5     106    F
6     107    G

In [12]:
df.loc[df.ROLLNO == 105]

ROLLNO NAME
4     105    E

In [16]:
df.loc[(df.ROLLNO > 102) & (df.ROLLNO < 105),["ROLLNO","NAME"]]

ROLLNO NAME
2     103    C
3     104    D